name: dphox
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - trimesh
  - shapely
  - pydantic
  - sphinx-autodoc-typehints
  - xarray
  - matplotlib
  - myst-parser
  - autodoc-pydantic