version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: doc/source/requirements.txt
    - method: setuptools
      path: .

sphinx:
  builder: html
  configuration: doc/source/conf.py