sudo: false
language: python
python:
  - 3.8
  - 3.9

before_install: &before_install
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment
  - source activate test-environment
  - conda install numpy matplotlib
  - conda install -c anaconda xarray
  - pip install pydantic gdspy trimesh klamath
  - conda install shapely descartes

install:
  pip install codecov && pip install pytest

script:
  coverage run -m pytest tests
after_success:
  - codecov

deploy:
  provider: pypi
  user: '__token__'
  password: 'pypi-AgEIcHlwaS5vcmcCJDQxNzRmOWYxLThkY2ItNGFlNC04YjAwLTQ0YjQ3NzIxMWU0YwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgFmQ2Qvr1GtGvdpuMPxsndt-7VjgSpTmXt_f4_0W_Dcc'
  on:
    branch: main
    tags: true
    python:
      - 3.8
      - 3.9